spring:
  application:
    name: e2e-tests
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/it_mentor_community_platform
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

docker:
  image:
    tags:
      gateway: ${GATEWAY_DOCKER_IMAGE_TAG:}
      auth-service: ${AUTH_SERVICE_DOCKER_IMAGE_TAG:}
      data-importer: ${DATA_IMPORTER_DOCKER_IMAGE_TAG:}
      profile-service: ${PROFILE_SERVICE_DOCKER_IMAGE_TAG:}
      project-service: ${PROJECT_SERVICE_DOCKER_IMAGE_TAG:}
      mentor-service: ${MENTOR_SERVICE_DOCKER_IMAGE_TAG:}
      job-market-analytics-service: ${JOB_MARKET_ANALYTICS_SERVICE_DOCKER_IMAGE_TAG:}

jwt:
  secret: 632eca39fc29068edc74133ca9cf8f40b4942191f80c0c78dd588835beb5f57b

telegram:
  init-data: user=%7B%22id%22%3A531455701%2C%22first_name%22%3A%22%D0%9C%D0%B0%D1%80%D0%BA%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22yeahigh%22%2C%22language_code%22%3A%22ru%22%2C%22photo_url%22%3A%22https%3A%5C%2F%5C%2Ft.me%5C%2Fi%5C%2Fuserpic%5C%2F320%5C%2FjeCwwKkabH7uU8K6ALqVFhodLV3KS-AXrt6vvm4okKc.svg%22%7D&chat_instance=-7061379911278325128&chat_type=supergroup&auth_date=1777060225&signature=uxESH6NQkg1q-otcmLaqjGJUF3tyKsYK3Sh98C2XpBBC2aZN3f-tJPfp8rV1OU0rj2VJYTgKBmjCX7IOcrpUBg&hash=2f1c5fb7b9cf74f1fcafbda3c800efb76ffb1117ea1358b4692e304806f5be6c
  updated-init-data: user=%7B%22id%22%3A531455701%2C%22first_name%22%3A%22%D0%9C%D0%B0%D1%80%D0%BA%22%2C%22last_name%22%3A%22%D0%A0%22%2C%22username%22%3A%22yeahigh%22%2C%22language_code%22%3A%22ru%22%2C%22photo_url%22%3A%22https%3A%5C%2F%5C%2Ft.me%5C%2Fi%5C%2Fuserpic%5C%2F320%5C%2FjeCwwKkabH7uU8K6ALqVFhodLV3KS-AXrt6vvm4okKc.svg%22%7D&chat_instance=3294457520524516638&chat_type=sender&auth_date=1777148749&signature=BLr0rSsq6Y-a-i5u2NxaWqIYohC_Mq6b4-15uYVS_w0Dztx_X7U4b2kdTcEuR5iRPb5YA3gYsDDpFkEVesboBw&hash=1bb1025a2e4cff2acfe37cf2e9648c81095659c9e760edeb7004cfa5a3bc9227

telegram-bot-adapter:
  auth:
    username: ${TELEGRAM_ADAPTER_USERNAME:username}
    password: ${TELEGRAM_ADAPTER_PASSWORD:password}

secrets:
  testcontainer-tag: ${TESTCONTAINER_DOCKER_IMAGES_TAG:dev}
  tg-token: ${TELEGRAM_BOT_TOKEN}
  hh:
    access-token: ${HH_APP_ACCESS_TOKEN}
    email: ${HH_APP_EMAIL}
  google:
    credentials-json: ${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    spreadsheet:
      source-id: ${GOOGLE_SOURCE_SPREADSHEET_ID}
      test-id: ${GOOGLE_TEST_SPREADSHEET_ID}
